var memes = [
    {
        image: "caesar.jpg", 
        title: "Julius Caesar",
        month:"January",
        year:"2016",
        categories: ["Rome","Halo","History"],
        meme_id: "1"
    },
    {
        image: "austria.jpg", 
        title: "Austria",
        month:"Febuary",
        year:"2016",
        categories: ["ww1","History"],
        meme_id: "2"
    },
    {
        image: "french.jpg", 
        title: "Renault",
        month:"March",
        year:"2016",
        categories: ["ww2","History"],
        meme_id: "3"
    },
    {
        image:"history-genocide.jpg",
        title:"Genocide",
        month:"April",
        year:"2016",
        categories:["ww2","History"],
        meme_id:"4"
    },
    {
        image:"history-japaneese.jpg",
        title:"Japaneese",
        month:"May",
        year:"2016",
        categories:["ww2","History"],
        meme_id:"5"
    },
    {
        image:"history-jeruselum.jpeg",
        title:"Dues Vult",
        month:"June",
        year:"2016",
        categories:["Classic","History"],
        meme_id:"5"
    },
    {
        image:"kennedy.jpg",
        title:"Kennedy",
        month:"July",
        year:"2016",
        categories:["Cold War","History"],
        meme_id:"6"
    },
    {
        image:"maginotline.jpg",
        title:"Maginotline",
        month:"August",
        year:"2016",
        categories:["ww2","History"],
        meme_id:"7"
    },
    {
        image:"maginotline2.jpg",
        title:"Retreat",
        month:"September",
        year:"2016",
        categories:["ww2","History"],
        meme_id:"8"
    },
    {
        image:"serbs.jpg",
        title:"Serbs",
        month:"October",
        year:"2016",
        categories:["Cold War","History"],
        meme_id:"9"
    },
    {
        image:"africa.jpg",
        title:"Democrocy",
        month:"November",
        year:"2016",
        categories:["History"],
        meme_id:"10"
    },
    {
        image:"austria2.jpg",
        title:"Austria",
        month:"December",
        year:"2016",
        categories:["ww1","History"],
        meme_id:"11"
    },
    {
        image:"france.jpg",
        title:"France",
        month:"January",
        year:"2017",
        categories:["ww2","ww1","History"],
        meme_id:"12"
    },
    {
        image:"stalin1.jpg",
        title:"Stalin",
        month:"Febuary",
        year:"2017",
        categories:["Cold War","History"],
        meme_id:"13"
    },
    {
        image:"sweden.jpg",
        title:"Nuetrality",
        month:"March",
        year:"2017",
        categories:["ww1","ww2","History"],
        meme_id:"14"
    },
    {
        image:"titanic.jpg",
        title:"Titanic",
        month:"April",
        year:"2017",
        categories:["History"],
        meme_id:"15"
    },
    {
        image:"trostky.jpg",
        title:"Trotsky",
        month:"May",
        year:"2017",
        categories:["History"],
        meme_id:"16"
    },
    {
        image:"worldwars.jpg",
        title:"WW",
        month:"June",
        year:"2017",
        categories:["History"],
        meme_id:"17"
    },
    {
        image:"youtube.jpg",
        title:"Youtube",
        month:"July",
        year:"2017",
        categories:["ww2","History"],
        meme_id:"18"
    },
    {
        image:"yuri.jpg",
        title:"Yuri",
        month:"August",
        year:"2017",
        categories:["Cold War","History"],
        meme_id:"19"
    },
    {
        image:"purchase.jpg",
        title:"America",
        month:"September",
        year:"2017",
        categories:["History"],
        meme_id:"20"
    },
    {
        image:"middle-east.jpg",
        title:"Sykes Picot",
        month:"October",
        year:"2017",
        categories:["History"],
        meme_id:"21"
    },
    {
        image:"moonrace.jpg",
        title:"Race",
        month:"November",
        year:"2017",
        categories:["","History"],
        meme_id:"22"
    },
    {
        image:"",
        title:"",
        month:"December",
        year:"2017",
        categories:["","History"],
        meme_id:"23"
    },
    {
        image:"",
        title:"",
        month:"",
        year:"2018",
        categories:["","History"],
        meme_id:"24"
    },
];